
package dam.tan.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonI", targetNamespace = "http://tan.dam/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonI {


    /**
     * 
     * @param arg0
     * @return
     *     returns dam.tan.client.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPerson", targetNamespace = "http://tan.dam/", className = "dam.tan.client.GetPerson")
    @ResponseWrapper(localName = "getPersonResponse", targetNamespace = "http://tan.dam/", className = "dam.tan.client.GetPersonResponse")
    @Action(input = "http://tan.dam/PersonI/getPersonRequest", output = "http://tan.dam/PersonI/getPersonResponse")
    public Person getPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
